In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000)
my_list = np.arange(1000)

In [5]:
data1 = [2,2.5,3,4.7,8.9,9.0]
array = np.array(data1,dtype = int)
print(array)
print(array.dtype)
print(array.shape)
print(array.ndim)

[2 2 3 4 8 9]
int32
(6,)
1


In [7]:
data2 = [[1,3,5,7,9,11],[2,4,6,8,10,12]] # both lists must have same number of elements
array2 = np.array(data2, dtype = int)
print(array2.ndim)
print(array2.shape)

2
(2, 6)


In [9]:
array3 = np.array([[1,3,5,7,9,11],[2,4,6,8,10,12]])
array3

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [11]:
array4 = np.eye(4, dtype = int)
array4

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])